# Generated by Django 6.0.5 on 2026-05-19 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='活动标题')),
                ('text', models.TextField(blank=True, null=True, verbose_name='活动描述')),
                ('date', models.DateField(verbose_name='举办活动日期')),
                ('count', models.IntegerField(default=0, verbose_name='报名人数')),
                ('total_count', models.IntegerField(default=0, verbose_name='总人数')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
            ],
            options={
                'verbose_name_plural': '活动表',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网格区域名')),
                ('desc', models.CharField(max_length=32, verbose_name='网格简称')),
            ],
            options={
                'verbose_name_plural': '区域表',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='banner1.png', upload_to='banner', verbose_name='图片')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('img', models.ImageField(default='notice.png', upload_to='notice', verbose_name='公告图片')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '公告表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('avatar', models.FileField(max_length=128, upload_to='avatar', verbose_name='头像')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='/welcome/slash.png', upload_to='welcome')),
                ('order', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '欢迎表',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='采集人员姓名')),
                ('name_pinyin', models.CharField(max_length=32, null=True, verbose_name='姓名拼音')),
                ('avatar', models.ImageField(default='default.png', upload_to='collection/%Y/%m/%d/', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('face_token', models.CharField(max_length=64, null=True, verbose_name='百度Token')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart02.area', verbose_name='网格区域')),
            ],
            options={
                'verbose_name_plural': '采集表',
            },
        ),
        migrations.CreateModel(
            name='JoinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart02.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart02.userinfo')),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
        migrations.AddField(
            model_name='area',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart02.userinfo', verbose_name='负责用户'),
        ),
        migrations.AddField(
            model_name='activity',
            name='join_record',
            field=models.ManyToManyField(through='smart02.JoinRecord', through_fields=('activity', 'user'), to='smart02.userinfo', verbose_name='参与者'),
        ),
    ]
